stages:
  - test

jobs:
  - name: test:rspec
    stage: test
    image: sunci/ruby:2.5.1
    before_script:
      - bundle install --path vendor/bundle
      - bundle exec rake db:structure:load db:migrate
    script:
      - bundle exec rspec --format progress --format  --out ./.sun-ci-reports/rspec.html spec --format junit --out ./.sun-ci-reports/coverage/junit.xml
    coverage:
      type: cobertura
      path: ./.sun-ci-reports/coverage/coverage.xml
    artifacts:
      paths:
        - ./.sun-ci-reports/coverage/
      expires_in: 3 days
    test_result:
      type: junit
      path: ./.sun-ci-reports/coverage/junit.xml
